CREATE TABLE [dbo].[GameSetting] (
    [GAMEBATCH]  INT            NOT NULL,
    [RATE]   NVARCHAR (100) NOT NULL,
    [PLAYER] NVARCHAR (200) NOT NULL,
    [LAND]   NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_GameSetting] PRIMARY KEY CLUSTERED ([GAMEBATCH] DESC)
);

