CREATE TABLE [dbo].[GameResult] (
    [GAMEBATCH]     INT            NOT NULL,
    [CONSUMEDROUND] INT            NOT NULL,
    [PLAYERINFO]    NVARCHAR (200) NOT NULL,
    [LANDINFO]      NVARCHAR (MAX) NOT NULL,
    [FIRSTROUNDPLAYER] NVARCHAR(200) NOT NULL, 
    [FIRSTROUNDLAND] NVARCHAR(MAX) NOT NULL, 
    CONSTRAINT [PK_GameResult] PRIMARY KEY CLUSTERED ([GAMEBATCH] DESC, [CONSUMEDROUND] DESC)
);

