USE [MonopolyRecord]
GO

/****** Object:  Table [dbo].[GameResult]    Script Date: 2023/3/15 ¤U¤È 03:37:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GameResult](
	[GAMEBATCH] [int] NOT NULL,
	[GAMENUMBER] [int] NOT NULL,
	[CONSUMEDROUND] [int] NOT NULL,
	[PLAYERINFO] [nvarchar](300) NOT NULL,
	[LANDINFO] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_GameResult] PRIMARY KEY CLUSTERED 
(
	[GAMEBATCH] DESC,
	[GAMENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


