USE [MonopolyRecord]
GO

/****** Object:  Table [dbo].[GameSetting]    Script Date: 2023/3/15 ¤U¤È 03:38:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GameSetting](
	[GAMEBATCH] [int] NOT NULL,
	[RATES] [nvarchar](100) NOT NULL,
	[PLAYERS] [nvarchar](300) NOT NULL,
	[LANDS] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_GANESETTINGPERBATCH] PRIMARY KEY CLUSTERED 
(
	[GAMEBATCH] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


